# Generated by Django 5.1.3 on 2024-11-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='uniName',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
